site_name: Haifeng's Notes
theme:
  name: 'material'
  palette:
    scheme: slate

docs_dir: notes
repo_url: https://github.com/haifeng-jin/notes 
site_url: https://notes.haifengjin.com
edit_uri: ""
site_description: "Haifeng Jin's Notes"
markdown_extensions:
  - codehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.arithmatex

extra_javascript:
  - https://unpkg.com/mermaid@8.4.4/dist/mermaid.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
nav:
  - Home: index.md
  - Math:
    - Test MathJax: math/test.md
  - Tech:
    - Snippets:
      - LaTex: tech/snippets/latex.md
      - Linux C Socket: tech/snippets/socket_c.md
      - ubuntu: tech/snippets/ubuntu.md
      - windows socket C++: tech/snippets/socket_cpp_win.md
      - Linux Commands: tech/snippets/linux_commands.md
      - Linux C Thread: tech/snippets/thread_c.md
      - GPU: tech/snippets/gpu.md
    - Tools:
      - TMUX: tech/tools/tmux.md
      - Jekyll: tech/tools/jekyll.md
      - Screen: tech/tools/screen.md
      - VIM Shortcuts: tech/tools/vim.md
      - Debugging with GDB | BetterExplained: tech/tools/gdb.md
      - Subversion: tech/tools/svn.md
      - Pycharm: tech/tools/pycharm.md
      - Docker: tech/tools/docker.md
      - Google Cloud Platform: tech/tools/gcp.md
    - Software Engineering:
      - Guide for Technical Development: tech/software_engineering/guide_for_technical_development.md
      - Java Log Best Practices: tech/software_engineering/java_log_best_practices.md
      - Design Review: tech/software_engineering/design_review.md
      - Unit Testing: tech/software_engineering/unit_testing.md
      - Refactor: tech/software_engineering/refactor.md
      - Agile: tech/software_engineering/agile.md
      - Python: tech/software_engineering/python.md
      - Design Patterns: tech/software_engineering/design_pattern.md
      - Git: tech/software_engineering/git.md
  - Review List: leetcode.md
